version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    reviewers: 
      - "xenit-eu/contentgrid"
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        update-types: ['version-update:semver-major']
      - dependency-name: org.springframework.cloud:spring-cloud-dependencies
        update-types: [ 'version-update:semver-major' ]
